plugins {
    id 'net.fabricmc.fabric-loom'
    id 'maven-publish'
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = rootProject.name
}

repositories {
    maven { url "https://maven.architectury.dev/" }
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    api "dev.architectury:architectury-fabric:${project.architectury_version}"
    api "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}"
    api "com.terraformersmc:modmenu:${project.modmenu_version}"
}

sourceSets.main.resources.srcDir rootProject.file('common')

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "projectName", rootProject.name

    from(rootProject.file("LICENSE")) {
        rename { "${it}_${rootProject.name}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }

    repositories {}
}
